### ISSUE TITLE
[06장: 쿠버네티스 시작하기] 6.2 포드(Pod) : 컨테이너를 다루는 기본 단위

### ISSUE THREAD

**Issue by engal1991** [engal1991/Docker-Kubernetes#21]
# 6.2.1 포드 사용하기

# 6.2.2 포드 vs. 도커 컨테이너

# 6.2.3 완전한 애플리케이션으로서의 포드

**Comment by yuodsa1** [comment]
> 291 ~ 296

## 6.2.1 포트 사용하기
 ** 포드는 쿠버네티스에서 가장 기본적이고, 중요한 개념이기에 확실히 알고 넘어가야합니다.

그럼 앞에서 봤던 다른 툴의 기본단위는??
 - 도커 엔진 : 도커 컨테이너
 - 스웜 모드 : 서비스(Service)
 - 쿠버네티스 :  **Pod** 

포드는 아래 그림과 같이 생겼다.
![image](https://user-images.githubusercontent.com/100204939/156547502-6b4c7813-bba3-4dba-a77b-b9bc140d51a4.png)
 * 노드 & 포드 & 컨테이너 의 관계가 중요..!! ( 몇일지나면 헷갈림.. )
> 출처 : https://wonizz.tk/2019/08/21/kubernetes-service/

아래는 앞에서 말한 것(#20 )과 같이 YAML파일을 많이 쓰기 때문에 예시로 나와있는 nginx 컨테이너가 들어가있는 포드를 생성하는 예시입니다.
```
apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
spec:
  containers:
  - name: my-nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP
```
포드의 속성
  - apiVersion : 이 오브젝트를 생성하기 위해 사용하고 있는 쿠버네티스 API 버전이 어떤 것인지 나타냄
  - kind : 리소스의 종류
  - spec : 포드 내 컨테이너의 스펙 ( 여기서는 nginx의 이미지, ports )

> 출처 
https://github.com/alicek106/start-docker-kubernetes/blob/master/chapter6/nginx-pod.yaml
https://lahuman.github.io/kubernetes-yaml/
