### ISSUE TITLE
[06장: 쿠버네티스 시작하기] 6.3 레플리카셋(Replica Set) : 일정 개수의 포드를 유지하는 컨트롤러

### ISSUE THREAD

**Issue by engal1991** [engal1991/Docker-Kubernetes#22]
# 6.3.1 레플리카셋을 사용하는 이유

# 6.3.2 레플리카셋 사용하기

# 6.3.3 레플리카셋의 동작 원리

# 6.3.4 레플리케이션 컨트롤러 vs. 레플리카셋

**Comment by yuodsa1** [comment]
> 301 ~ 303p

## 6.3.1 레플리카셋을 사용하는 이유

replica set 은 레플리카셋의 목적은 레플리카 포드 집합의 실행을 항상 안정적으로 유지하는 것을 목적으로 만들어진 오브젝트이다.

포드를 여러개 띄우는 방식은 어떤게 있을까?
1. 하나의 yaml파일에 노다가 정신으로 여러개의 포드를 입력해서 띄울수도 있고,
2. 또 다른 노다가 정신으로 kubectl 을 활용하여 여러번의 타이핑으로 띄울수도 있고...

위 방법들로도 물론 여러 포드를 띄울 수 있지만, 만약 이것들이 죽으면?? 살아날까??
답은 영원히 죽어있습니다.

그렇다면 쿠버네티스의 목적인 오케스트레이션에 알맞은 방법은 무엇인가.. 이게 바로 replica set 이다.
replica set 은 #20 에서 언급했듯 ``` 컨트롤 플레인 컴포넌트 ``` 인 kube-controll-manager 의 관리하에서 포드들의 일정 개수를 유지하는 오브젝트입니다.


> 출처
https://kubernetes.io/ko/docs/concepts/overview/components/#cloud-controller-manager

**Comment by yuodsa1** [comment]
> 303 ~ 306p

## 6.3.2 레플리카셋 사용하기

레플리카셋 역시 YAML파일로 생성 및 관리가 된다. 아래는 #21 에서 nginx pod를 생성하는 YAML파일에서 여러개가 추가된 모습이다.

```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-nginx
spec:                                        -- [ 0 ] 
  replicas: 3
  selector:
    matchLabels:
      app: my-nginx-pods-label               -- [ 1 ] 
  template:
    metadata:
      name: my-nginx-pod
      labels: 
        app: my-nginx-pods-label
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

```

어떤 부분이 어디의 설정인가를 보면

 - 레플리카셋
      [0] 번 spec을 기준으로 [1] 까지는 레플리카셋에 대한 설정이다. 레플레카셋도 어떤 레플리카셋인지 구분하기 위해 ``` selector.matchLabels.app ``` 이라는 라벨을 달려졌고, ``` spc.replicas ``` 라는 속성을 통해 무슨 일이 있어도 아래 정의한 포드의 개수는 3개 유지해라 로 정의되있습니다.

 - 포드
     [1] 번을 기준으로 아래는 포드에 대한 정의입니다. 크게 별 다른 점은 #21 의 예제와 다를바가 없고, depth가 spec.template이 추가되어 더 싶어진 것이 달라진 점이다.

>출처
https://github.com/alicek106/start-docker-kubernetes/blob/master/chapter6/replicaset-nginx.yaml
