### ISSUE TITLE
[06장: 쿠버네티스 시작하기] 6.5 서비스(Service) : 포드를 연결하고 외부에 노출

### ISSUE THREAD

**Issue by engal1991** [engal1991/Docker-Kubernetes#24]
# 6.5.1 서비스(Service)의 종류

# 6.5.2 ClusterIP 타입의 서비스 - 쿠버네티스 내부에서만 포드에 접근하기

# 6.5.3 NodePort 타입의 서비스 - 서비스를 이용해 포드를 외부에 노출하기

# 6.5.4 클라우드 플랫폼의 로드 밸런서와 연동하기 - LoadBalancer 타입의 서비스

# 6.5.5 트래픽의 분배를 결정하는 서비스 속성 - externalTrafficPolicy

# 6.5.6 요청을 외부로 리다이렉트하는 서비스 - ExternalName

**Comment by yuodsa1** [comment]
열심히 만든 파드, 레플리카셋, 디플로이먼트가 외부에 접근이 되지않습니다.
도커는 -p 옵션을 통해 쉽게 외부에 노출할 수 있었지만, 쿠버네티스는 그렇지 않습니다.
외부와의 연결을 위해 서비스라는 오브젝트가 필수적으로 필요합니다.

서비스는 아래의 핵심기능을 가지고 있습니다.
 - 포드들에 쉽게 접근하도록 도메인을 지원
 - 로드밸런서
 - 클라우드 플랫폼의 로드 밸런서, 클러스터 노드의 포트 등을 통해 포드를 외부로 노출

> 318 ~ 322

### 6.5.1 서비스(Service)의 종류

서비스는 3개의 타입을 가지고 있습니다.
 - clusterIp 타입 : 쿠버네티스 내부에서만 포드에 접근할 떄 사용
 - nodeport 타입 : 포드에 접근할 수 있는 포드를 컨테이너의 모든 노드에 동일하게 개방해 외부에서 포드에 접근할 수 있음
 - loadbalancer 타입 : nodeport와 같지만, 클라우드 플랫폼에서 사용하는 nodeport 타입

**Comment by yuodsa1** [comment]
> 322 ~ 326

6.5.2 ClusterIP 타입의 서비스 - 쿠버네티스 내부에서만 포드에 접근하기
-

아래 예시는 ClusterIP타입 서비스에 대한 정의입니다.

```
apiVersion: v1
kind: Service
metadata:
  name: hostname-svc-clusterip
spec:
  ports: - [2~]
    - name: web-port
      port: 8080
      targetPort: 80 [~3]
  selector:
    app: webserver - [1]
  type: ClusterIP
```

[1] : 해당 라벨을 가지는 포드에 접근할 수 있는 서비스를 만들겠다는 선언
[2~3] : [1]에서 정의한 포드 라벨에 더하여 정의한 포드들이 사용하는 포트를 선언
Q) 파드에서 외부로 노출할(= 디플로이먼트에서 정의한) 포트는 다 적어야하는 걸까? 내가 쓰고 싶은 포트만 적어도 될까?
서비스를 만드는 의미가 없겠구나 이건 ㅋㅋㅋ

clusterIP 인 경우 호출은 어떻게 할까?
```
서비스의 이름 또는 IP + 포트
서비스 이름 : hostname-svc-clusterip
서비스 IP : 102.10.1.1
포트 : 8080

hostname-svc-clusterip:8080
Or
102.10.1.1:8080

```

**Comment by yuodsa1** [comment]
> 326 ~ 330

### 6.5.3 NodePort 타입의 서비스 - 서비스를 이용해 포드를 외부에 노출하기

이제는 외부에서 접근이 가능합니다.
NodePort는 말그대로 Node의 문(=포트)를 열어 파드에 접근할 수 있게 해주는 서비스입니다.

```
apiVersion: v1
kind: Service
metadata:
  name: hostname-svc-nodeport
spec:
  ports:
    - name: web-port
      port: 8080
      targetPort: 80
  selector:
    app: webserver
  type: NodePort


```

> ClusterIP와 spec.type 말고는 다 같습니다.


NodePort 타입의 서비스를 생성하고, 외부에서 호출을 딱! 하면
모든 노드에 해당 포트로 요청이 보내지고, 선언된 서비스 내에 연결된 파드에 라우팅이 됩니다.

?

근데 외부에 노출될 포트는 따로 설정을 안했는데 어떻게 접근하지???

포트는 내가 직접 선언하던가, 랜덤으로 얻을 수 있다.
쿠버네티스에서는 시스템상으로 사용하는 포트가 있어 이를 피하기 위해 저 멀리 떨어져있는 기본적으로 30000 ~ 32768 번 사이의 포트를 랜덤으로 할당해주거나 선언 할 수 있다.

```
in yaml 파일
sepc:
  ports:
    - name : web-port
      nodePort: 32111
```
