### ISSUE TITLE
[07장: 쿠버네티스 리소스의 관리와 설정] 7.1 네임스페이스(Namespace) : 리소스를 논리적으로 구분하는 장벽

### ISSUE THREAD

**Issue by engal1991** [engal1991/Docker-Kubernetes#25]

**Comment by yuodsa1** [comment]
> 341

일종의 논리 그룹

네임스페이스 조회
> kubectl get ns or kubectl get namespace

A 네임스페이스의 오브젝트 조회
> kubetcl get pods -n A

### 네임스페이스 사용하기

```
apiVersion: v1
kind: Namespace
metadata:
  name: production


$ kubectl apply -f namespace.yaml
```

네임스페이스를 생성했으면 이 네임스페이스에 속하는 오브젝트를 만들때는 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-deployment-ns
  namespace: production - [1]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: my-webserver
      labels:
        app: webserver
    spec:
      containers:
      - name: my-webserver
        image: alicek106/rr-test:echo-hostname
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hostname-svc-clusterip-ns
  namespace: production - [1]
spec:
  ports:
    - name: web-port
      port: 8080
      targetPort: 80
  selector:
    app: webserver
  type: ClusterIP

```

위 선언한 namespace 의 name을 오브젝트 yaml에 기재하면 된다. ( [1] )

### 네임스페이스의 서비스에 접근하기

#24 에 언급한 서비스에서의 설명은 쿠버네티스를 설치하면 기본적으로 생성되는 default-namepsace에 생성됩니다. 그렇기에 위 예제의 production 네임스페이스에서는 default-namespace의 서비스에는 접근을 하지 못합니다.

다만, [서비스이름].[네임스페이스이름][svc] 처럼 접근이 가능합니다.
```
example
curl hostname-svc-clusterip-ns.production.svc:8080 --silent | grep Hello
```

추가로, 네임스페이스를 삭제하면 pasta에서 워크스페이스 삭제되면 그 하위가 모두 사라지듯 마찬가지로 하위 모든 오브젝트는 삭제됩니다.

### 네임스페이스에 종속되는 쿠버네티스 오브젝트와 독립적인 오브젝트

 * 포드나 레플리카셋과 같은 개발자가 만들어 사용하는 오브젝트가 아닌, 실제 쿠버네티스를 관리하기 위한 아래의 오브젝트(nodes, namespace) 등은 네임스페이스에 종속되지않은 저수준의 오브젝트들이 해당됩니다.
```
$kubectl get pods, ns
```
