### ISSUE TITLE
[10장: 보안을 위한 인증과 인가 - ServiceAccount와 RBAC] 10.1 쿠버네티스의 권한 인증 과정

### ISSUE THREAD

**Issue by engal1991** [engal1991/Docker-Kubernetes#35]
쿠버네티스에서는 RBAC(Role Based Access Control)를 기반으로 하는 서비스 어카운트 (Service Account)라는 기능이 보안에 많이 사용된다.
리눅스 root 유저와 일반 유저를 나누는 기능과 유사하다.

**Comment by engal1991** [comment]
**인증 과정**
1. 클라이언트가 kubectl 명령어로 쿠버네티스 API 서버의 HTTP 핸들러에 요청 전송
2. 해당 클라이언트가 쿠버네티스의 사용자가 맞는지 인증(Authentication) 및 권한이 있는지 인가 (Authorization) 확인
3. 어드미션 컨트롤러 수행
4. 요청 수행

**쿠버네티스 기본 권한**
`.kube/config`를 보면 기본적으로 최고 권한을 갖고있는걸 확인할 수 있다.
```
...
users:
- name: kubernetes-admin <=
  user:
    client-certification-data: XXX
    client-key-data: XXX
...
```
