### ISSUE TITLE
[10장: 보안을 위한 인증과 인가 - ServiceAccount와 RBAC] 10.4 서비스 어카운트에 이미지 레지스트리 접근을 위한 시크릿 설정

### ISSUE THREAD

**Issue by engal1991** [engal1991/Docker-Kubernetes#38]
7장에서 레지스트리 인증 정보를 저장하는 별도의 시크릿을 생성했다.
```
1) ./docker/config.json 사용하기
kubectl create secret generic registry-auth \
-- from-file=.dockerconfigjson=/root/.docker/config.json \
--type=kubernetes.io/dockerconfigjson

2) 직접 입력하기
kubectl create secret docker-registry registry-auth-registry \
--docker-username=<user name>
--docker-password=<passwd>
--docker-server=<docker registry>
```

서비스 어카운트를 이용하면 비공개 레지스트리 접근을 위한 시크릿을 서비스 어카운트 전체에 설정할 수 있다.
```
apiVersion: v1
kind: ServiceAccount
meta-data:
  name: <service account name>
  namespace: <namespace name>
imagePullSecrets:
- name: <docker-registry secret name>
```
