### ISSUE TITLE
[12장: 커스텀 리소스와 컨트롤러] 12.1 쿠버네티스 컨트롤러의 개념과 동작 방식

### ISSUE THREAD

**Issue by engal1991** [engal1991/Docker-Kubernetes#45]

**Comment by yuodsa1** [comment]
### 12.1 쿠버네티스 컨트롤러의 개념과 동작 방식

명령형(Imprerative) vs 선언적(Declarative)
 - 명령형 : 처리하는 주체와 통신해 그 작업을 수행하고 그 결괏값을 돌려받는 방식(= docker run ~, ps ef | grep nginx )
 - 선언형 : 설정한 값이 시스템적으로(= 자동적으로) 조절되게끔 유지되게 하는 방식(= 포드가 죽으면 다른 포드로 부활)

요 선언형이 쿠버네티스의 주요한 개념인데 아래와 같이 명령어를 입력하면 <파일>에 내가 기재한 스펙이 완성되게끔 처리하는게 ``` 컨트롤러 ``` 가 내부적으로 결정합니다. == 쿠버네티스를 보다 깊게 이해할려면 컨트롤러를 잘 알아야함
```
$ kubectl apply -f <파일>
```

![image](https://user-images.githubusercontent.com/100204939/157855297-cbfeb6e6-5b5b-4047-a1f5-4478319cf076.png)

* etcd : 쿠버네티스에서의 DB같은 역활, API 서버에서 받은 데이터를 저장하는 역활을 함

> 출처 : https://velog.io/@hidaehyunlee/%EC%BF%A0%EB%B2%84%EB%84%A4%ED%8B%B0%EC%8A%A4-%EC%95%84%ED%82%A4%ED%85%8D%EC%B2%98-1.-%EA%B5%AC%EC%84%B1-%EB%B0%8F-%EC%84%A4%EA%B3%84

**Comment by yuodsa1** [comment]
### 12.2 커스텀 리소스에 대한 개념

커스텀 리소스 = 개발자가 만들어놓은 리소스( like pasta > jenkins )

#### 커스텀 리소스를 사용하기 위한 단계
1. yaml 파일 > kind 에 내가 적은 리소스를 넣으면, 이를 바람직하게 만들수있도록 컨트롤러를 구현하고, 이를 실행
2. 상세 정보를 정의하는 CRD( Custom Resource Definition ) 리소스를 생성
3. CRD를 레시피로 리소스 생성
4. 컨트롤러에서 watch해서 적절한 작업 수행

**Comment by yuodsa1** [comment]
### 12.3 커스텀 리소스를 정의하기 위한 CRD

CRD는 커스텀 리소스를 사용하기 위한 정의서(= 레시피) 입니다.

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alices.k106.com  # 1. CRD의 이름
spec:
  group: k106.com      # 2. 커스텀 리소스의 API 그룹
  version: v1alpha1     #    커스텀 리소스의 API 버전
  scope: Namespaced   #    커스텀 리소스가 네임스페이스에 속하는지 여부
  names:
    plural: alices        # 3. 커스텀 리소스의 이름 (복수형)
    singular: alice      #    커스텀 리소스의 이름 (단수형)
    kind: Alice         #    YAML 파일 등에서 사용될 커스텀 리소스의 Kind
    shortNames: ["ac"] #    커스텀 리소스 이름의 줄임말
  validation:
    openAPIV3Schema:    # 4. 커스텀 리소스의 데이터를 정의
      required: ["spec"]   #   커스텀 리소스에는 반드시 "spec" 이 존재해야 함.
      properties:         #    커스텀 리소스에 저장될 데이터 형식을 정의
        spec:
          required: ["myvalue"]
          properties:
            myvalue:
              type: "string"
              minimum: 1
```
