### ISSUE TITLE
[13장: 포드를 사용하는 다른 오브젝트들] 13.1 잡(Jobs)

### ISSUE THREAD

**Issue by engal1991** [engal1991/Docker-Kubernetes#49]

**Comment by yuodsa1** [comment]
잡의 목적 : 특정 동작 수행 후 종료(= 우리가 흔히 생각하는 배치잡)

잡은 레플리카셋과 비슷하다고 생각하면 됩니다.( 포드를 지정한 개수만큼 생성한다는 점만)
또한 디플로이먼트+레플리카셋+포드 와 다른 점은 앞의 3셋은 특정 개수의 포드가 실행중인 것이 최종상태라면,
잡은 포드가 실행되어 정상적으로 종료되는 것 이라고 생각하면 됩니다.

레플리카셋과 마찬가지로 잡 하위에서 파드가 생성되어 지정한 행동을 실행하는데, 잡은 최종상태가 ``` 종료 ``` 되는 것이기 때문에, 파드의 최종상태를 Naver or OnFailure 로 지정해줘야합니다.

### 잡의 세부 옵션

```
apiVersion: batch/v1
kind: Job
metadata:
  name: job-completions
spec:
  completions: 3 # 몇개의 포드가 성공해야 이 잡이 성공했다고 볼수있는지
  parallelism: 1 # 동시에 생성될 포드의 개수 , default 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: busybox
        args: ["sh", "-c", "echo Hello, World && exit 0"]
        name: job-completions
```
> 위와 같이 설정하면 포드가 1->2->3 이렇게 순서를 가지고 실행 ( 1번 성공 -> 2번 생성 -> 2번 성공 -> ... )

### 크론잡

우리가 서버의 로그들을 일별로, 시간별로 분리하기 위한 스케쥴링
쿠버네티스에서의 크론잡 오브젝트는 로그 대신 잡은 주기적으로 실행하는 오브젝트

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-example
spec:
  schedule: "*/1 * * * *"        # Job의 실행 주기
  jobTemplate:                 # 실행될 Job의 설정 내용 (spec)
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: cronjob-example
            image: busybox
            args: ["sh", "-c", "date"]
```
